services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=blog
      - DB_USERNAME=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - blog-network
  
  db:
    image: postgres:15
    container_name: blog_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge